void testSymbole (codesLex cl, codesErr err);
void premierSym();
void program();
void block();
void consts();
void vars();
void insts();
void inst();
void affec();
void si();
void tantque();
void ecrire();
void lire();
void cond();
void expr();
void term();
void fact();